name: cache-dataset
description: Use cache for test data

inputs:
  TEST_DATA_PASSWORD:
    description: 'Password to download test data'
    required: true

runs:
  using: composite
  steps:
      - name: Get test data md5sum
        run: |
          export TESTDATA_MD5SUM=`grep 'TESTDATA_MD5SUM' ./tests/conftest.py | awk -F"'" '{print $2}' | tr -d '\n'`
          echo "TESTDATA_MD5SUM=${TESTDATA_MD5SUM}" >> "$GITHUB_ENV"
          echo $TESTDATA_MD5SUM
        shell: bash

      - name: Try to restore test datafrom cache
        id: cache-testdataset
        uses: actions/cache/restore@v3
        with:
          path: $HOME/iop4testdata.tar.gz
          key: ${{ env.TESTDATA_MD5SUM }}

      - name: Download test data if cache was not found
        if: steps.cache.outputs.cache-hit != 'true'
        env:
          TEST_DATA_PASSWORD: ${{ input.TEST_DATA_PASSWORD }}
          TESTDATA_MD5SUM: ${{ env.TESTDATA_MD5SUM }}
        run:  | 
          wget --post-data "pass=$TEST_DATA_PASSWORD" "https://vhega.iaa.es/iop4/iop4testdata.tar.gz?md5sum=$TESTDATA_MD5SUM" -O $HOME/iop4testdata.tar.gz
        shell: bash
      
      - name: Save to cache if cache was not found
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v3
        with:
          path: $HOME/iop4testdata.tar.gz
          key: ${{ env.TESTDATA_MD5SUM }}