name: CI


# by not building all branches on push, we avoid the duplicated builds in PRs
on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request:

concurrency:
  # cancel previous runs of the same workflow for the same PR when new commits are pushed
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  NUMBA_NUM_THREADS: 1
  MPLBACKEND: Agg
  PYTEST_ADDOPTS: --color=yes


jobs:

  test-selfhosted:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.9"
      
      - name: Update pip
        run: |
          python -m pip install --upgrade pip

      - name: Install doc dependencies
        run: |
          pip install -e .[doc]
          python -c 'import iop4lib; print(iop4lib.__version__)'