name: Deploy to PyPi

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.9

      - name: Install dependencies
        run: |
          python --version
          pip install -U build
          python -m build
      - name: Store the distribution packages
        uses: actions/upload-artifact@v3
        with:
          name: python-package-distributions
          path: dist/

  publish-to-pypi:
      name: Publish Python distribution to PyPI
      if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
      needs:
      - build
      runs-on: ubuntu-latest
      environment:
        name: pypi
        url: https://pypi.org/p/iop4 
      permissions:
        id-token: write 
      steps:
        - name: Download all the dists
          uses: actions/download-artifact@v4.1.7
          with:
            name: python-package-distributions
            path: dist/
        - name: Publish distribution to PyPI
          uses: pypa/gh-action-pypi-publish@release/v1